name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  upload:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact_id }}
    steps:
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        id: upload
        with:
          path: ./docs

  deploy:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
