name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  upload:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        id: upload
        with:
          path: ./docs

  deploy:
    needs: upload
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
